const PDFDocument = require("pdfkit");
const db = require("../models/database"); // Replace with your database logic file
const fs = require("fs");
const path = require("path");

// Route to generate the PDF report
exports.activeTrainsReport = (req, res) => {
  console.log("hereeeeeee");
  const trains = db.getActiveTrains();
  const doc = new PDFDocument({ margin: 40 });
  const logoPath = path.join(__dirname, "../public/images/logo.jpg");
  const arabicFontPath = path.join(__dirname, "../fonts/Amiri-Regular.ttf"); // Arabic font path

  // Set headers for file download
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader(
    "Content-Disposition",
    'attachment; filename="Train_Report.pdf"'
  );

  doc.pipe(res);

  // Register and use the Arabic-compatible font
  doc.registerFont("ArabicFont", arabicFontPath);

  // Add the logo
  try {
    doc.image(logoPath, { width: 120, align: "center" }).moveDown(2);
  } catch (err) {
    console.log("Logo not found, skipping...");
  }

  // Add the title
  doc
    .fontSize(26)
    .fillColor("#333")
    .text("Train Schedule Report", { align: "center" })
    .moveDown(2);

  // Add each train's details
  trains.forEach((train, index) => {
    doc
      .fontSize(16)
      .fillColor("#007bff")
      .text(`Train ${index + 1}: ${train.EnglishName}`, { align: "left" })
      .font("ArabicFont") // Switch to Arabic font
      .text(`(${train.ArabicName})`, { align: "left" })
      .moveDown(0.5)
      .fontSize(12)
      .fillColor("#000")
      .text(`From: ${train.FromStation}`, { indent: 20 })
      .text(`To: ${train.ToStation}`, { indent: 20 })
      .text(`Departure: ${train.DepartureTime}`, { indent: 20 })
      .text(`Arrival: ${train.ArrivalTime}`, { indent: 20 })
      .moveDown(1)
      .strokeColor("#ddd")
      .lineWidth(0.5)
      .moveTo(40, doc.y)
      .lineTo(555, doc.y)
      .stroke()
      .moveDown(1);
  });

  // Add a footer
  doc
    .moveDown(2)
    .fontSize(10)
    .fillColor("#666")
    .text("Generated by Tareeq Rail System", 40, 750, { align: "left" })
    .text("Report generated on: " + new Date().toLocaleString(), 40, 765, {
      align: "left",
    });

  // Finalize the document
  doc.end();
};
